### ISSUE TITLE
Request for the dataset

### ISSUE THREAD

**Issue by FutabaSakuraXD** [xujinglin/MvNNcor#1]
作者您好，

最近有幸读到您在2020年于AAAI发表的论文“Deep Embedded Complementary and Interactive Information for Multi-View Classification”，并且现在正着手复现里面的结果。但我发现，由数据集官方下载链接所得到的文件和代码中所支持的格式不太匹配。因此能否请发我一份这份代码所支持的数据集文件 (51194501066@stu.ecnu.edu.cn)？感激不尽。

Sincerely,
Florence

**Comment by xujinglin** [comment]
Hi, thanks for your interest in our work.

Could point out which dataset has the data format problem?

**Comment by xujinglin** [comment]
> 

Hi, thanks for your interest in our work.

Could point out which dataset has the data format problem?

**Comment by xujinglin** [comment]
> 作者您好，
> 
> 最近有幸读到您在2020年于AAAI发表的论文“Deep Embedded Complementary and Interactive Information for Multi-View Classification”，并且现在正着手复现里面的结果。但我发现，由数据集官方下载链接所得到的文件和代码中所支持的格式不太匹配。因此能否请发我一份这份代码所支持的数据集文件 ([51194501066@stu.ecnu.edu.cn](mailto:51194501066@stu.ecnu.edu.cn))？感激不尽。
> 
> Sincerely, Florence

Hi, thanks for your interest in our work.

Could you point out which dataset has the data format problem?

**Comment by FutabaSakuraXD** [comment]
Many thanks for this response: )

Would you please share the Reuters, Hand, NUSOBJ, Caltech-101? Cause I found none of the downloaded *.mat files include the key of 'lenSmp' and 'feanames'.

Thanks for your time.

**Comment by FutabaSakuraXD** [comment]
> > 作者您好，
> > 最近有幸读到您在2020年于AAAI发表的论文“Deep Embedded Complementary and Interactive Information for Multi-View Classification”，并且现在正着手复现里面的结果。但我发现，由数据集官方下载链接所得到的文件和代码中所支持的格式不太匹配。因此能否请发我一份这份代码所支持的数据集文件 ([51194501066@stu.ecnu.edu.cn](mailto:51194501066@stu.ecnu.edu.cn))？感激不尽。
> > Sincerely, Florence
> 
> Hi, thanks for your interest in our work.
> 
> Could you point out which dataset has the data format problem?

Many thanks for this response: )

Would you please share the Reuters, Hand, NUSOBJ, Caltech-101? Cause I found none of the downloaded *.mat files include the key of 'lenSmp' and 'feanames'.

Thanks for your time.

**Comment by xujinglin** [comment]
You need to select the corresponding ".py" in the folder "dataset" according to different datasets, and modify the line 27 "https://github.com/xujinglin/MvNNcor/blob/24dab9aadf51cc2dfd9e128f368e5e4fcae6832b/MvNNcor_Train.py#L27".

In addition, the data form and path of AWA are different from those of other datasets. You also need to modify the path in line 35 "https://github.com/xujinglin/MvNNcor/blob/24dab9aadf51cc2dfd9e128f368e5e4fcae6832b/MvNNcor_Train.py#L35".

**Comment by FutabaSakuraXD** [comment]
Dear author,


Thanks for the tips and sharing : )


Yours,
Florence.
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Sat, Apr 2, 2022 04:13 PM
To: ***@***.***&gt;; 
Cc: ***@***.******@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [xujinglin/MvNNcor] Request for the dataset (Issue #1)

&nbsp;



 
You need to select the corresponding ".py" in the folder "dataset" according to different datasets, and modify the line 27 "https://github.com/xujinglin/MvNNcor/blob/24dab9aadf51cc2dfd9e128f368e5e4fcae6832b/MvNNcor_Train.py#L27".
 
In addition, the data form and path of AWA are different from those of other datasets. You also need to modify the path in line 35 "https://github.com/xujinglin/MvNNcor/blob/24dab9aadf51cc2dfd9e128f368e5e4fcae6832b/MvNNcor_Train.py#L35".
